### PR TITLE
Partition .meshes()

### PR DESCRIPTION
**Pull request by Fil**
For #17.

### CODE REVIEW

**Comment by niamleeson** [comment]
Any progress on this?

**Comment by Fil** [comment]
I still think it's a good idea, but if it should live in a different project (like topojson-tools or something), why not.

btw I've just fixed my block which was sort of broken (because the json file had disappeared).

**Comment by ghost** [comment]
Interested in getting this merged

**Comment by Fil** [comment]
A simpler version is now available in https://observablehq.com/@fil/tagged-borders ; it's just one function that can be copied in your application.

**Pull request closed without merging**
